Repository woowa-techcamp-2024/Team6-Drive, pull requests merged in 2024-08, with the labels that each got.

#8 [BE] 유저 생성 및 조회 기능 구현
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadata.java
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadataFactory.java
  src/main/java/com/woowacamp/storage/domain/user/controller/UserController.java
  src/main/java/com/woowacamp/storage/domain/user/dto/UserDto.java
  src/main/java/com/woowacamp/storage/domain/user/dto/request/CreateUserReqDto.java
  src/main/java/com/woowacamp/storage/domain/user/entity/User.java
  src/main/java/com/woowacamp/storage/domain/user/entity/UserFactory.java
  src/main/java/com/woowacamp/storage/domain/user/service/UserService.java
Labels: ✅기능 개발

#9 UserService 컴파일 오류 수정 및 S3 설정값 .yml에서 주입받는 방식으로 수정
  .gitignore
  build.gradle
  src/main/java/com/woowacamp/storage/domain/user/dto/request/CreateUserReqDto.java
  src/main/java/com/woowacamp/storage/domain/user/service/UserService.java
  src/main/java/com/woowacamp/storage/global/config/S3Configuration.java
  src/main/java/com/woowacamp/storage/global/error/ErrorCode.java
  src/main/resources/application.yml
Labels: 🐞버그 해결

#11 [BE] 파일 및 폴더를 생성한다.
  src/main/java/com/woowacamp/storage/StorageApplication.java
  src/main/java/com/woowacamp/storage/domain/file/controller/AsyncFileControllerV1.java
  src/main/java/com/woowacamp/storage/domain/file/controller/FileController.java
  src/main/java/com/woowacamp/storage/domain/file/controller/SyncFileControllerV1.java
  src/main/java/com/woowacamp/storage/domain/file/dto/FileMetadataDto.java
  src/main/java/com/woowacamp/storage/domain/file/dto/FormMetadataDto.java
  src/main/java/com/woowacamp/storage/domain/file/dto/PartContext.java
  src/main/java/com/woowacamp/storage/domain/file/dto/UploadContext.java
  src/main/java/com/woowacamp/storage/domain/file/dto/UploadState.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadata.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadataFactory.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/file/service/FileWriterThreadPool.java
  src/main/java/com/woowacamp/storage/domain/file/service/S3FileService.java
  src/main/java/com/woowacamp/storage/domain/file/util/CustomS3BlockingQueuePolicy.java
  src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/request/CreateFolderReqDto.java
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadata.java
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadataFactory.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
  src/main/java/com/woowacamp/storage/domain/user/dto/request/CreateUserReqDto.java
  src/main/java/com/woowacamp/storage/domain/user/service/UserService.java
  src/main/java/com/woowacamp/storage/global/config/MultipartConfiguration.java
  src/main/java/com/woowacamp/storage/global/constant/CommonConstant.java
  src/main/java/com/woowacamp/storage/global/error/ErrorCode.java
  src/main/java/com/woowacamp/storage/global/error/GlobalExceptionHandler.java
  src/main/java/com/woowacamp/storage/global/scheduler/AbortedUploadDeleteScheduler.java
  src/main/resources/application.yml
Labels: ✅기능 개발

#10 [BE] 폴더를 조회한다.
  build.gradle
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadata.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileCustomRepository.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileCustomRepositoryImpl.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataJpaRepository.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/CursorType.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/CursorTypeConverter.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/FolderContentsDto.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/FolderContentsSortField.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/FolderContentsSortFieldConverter.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/GetFolderContentsRequestParams.java
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadata.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepositoryImpl.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataJpaRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
  src/main/java/com/woowacamp/storage/domain/user/controller/UserController.java
  src/main/java/com/woowacamp/storage/domain/user/dto/request/CreateUserReqDto.java
  src/main/java/com/woowacamp/storage/domain/user/service/UserService.java
  src/main/java/com/woowacamp/storage/global/config/QueryDSLConfig.java
  src/main/java/com/woowacamp/storage/global/config/S3Configuration.java
  src/main/java/com/woowacamp/storage/global/constant/UploadStatus.java
  src/main/java/com/woowacamp/storage/global/error/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/com/woowacamp/storage/domain/folder/dto/FolderContentsSortFieldTest.java
  src/test/java/com/woowacamp/storage/domain/folder/service/FolderServiceTest.java
  src/test/resources/application-test.yml
Labels: ✅기능 개발

#16 [BE] 폴더 및 파일 삭제 기능
  src/main/java/com/woowacamp/storage/domain/file/controller/FileController.java
  src/main/java/com/woowacamp/storage/domain/file/controller/MultipartFileController.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadata.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/file/service/FileService.java
  src/main/java/com/woowacamp/storage/domain/file/service/S3FileService.java
  src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
  src/main/java/com/woowacamp/storage/global/constant/CommonConstant.java
  src/main/java/com/woowacamp/storage/global/error/ErrorCode.java
  src/main/java/com/woowacamp/storage/global/error/GlobalExceptionHandler.java
  src/main/java/com/woowacamp/storage/global/scheduler/OrphanFileDeleteScheduler.java
Labels: ✅기능 개발

#17 [BE] 파일 및 폴더를 이동한다.
  src/main/java/com/woowacamp/storage/domain/file/controller/FileController.java
  src/main/java/com/woowacamp/storage/domain/file/controller/MultipartFileController.java
  src/main/java/com/woowacamp/storage/domain/file/dto/FileMoveDto.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadata.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/file/service/FileService.java
  src/main/java/com/woowacamp/storage/domain/file/service/S3FileService.java
  src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/request/FolderMoveDto.java
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadata.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataJpaRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
  src/main/java/com/woowacamp/storage/domain/folder/utils/FolderSearchUtil.java
  src/main/java/com/woowacamp/storage/global/error/ErrorCode.java
  src/main/java/com/woowacamp/storage/global/scheduler/OrphanFileDeleteScheduler.java
Labels: ✅기능 개발

#21 [BE] 파일/폴더를 공유하는 링크를 생성한다.
  src/main/java/com/woowacamp/storage/domain/file/service/S3FileService.java
  src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
  src/main/java/com/woowacamp/storage/domain/shredlink/controller/SharedLinkController.java
  src/main/java/com/woowacamp/storage/domain/shredlink/dto/request/MakeSharedLinkRequestDto.java
  src/main/java/com/woowacamp/storage/domain/shredlink/dto/response/SharedLinkResponseDto.java
  src/main/java/com/woowacamp/storage/domain/shredlink/entity/PermissionType.java
  src/main/java/com/woowacamp/storage/domain/shredlink/entity/SharedLink.java
  src/main/java/com/woowacamp/storage/domain/shredlink/entity/SharedLinkFactory.java
  src/main/java/com/woowacamp/storage/domain/shredlink/service/SharedLinkService.java
  src/main/java/com/woowacamp/storage/global/constant/CommonConstant.java
  src/main/java/com/woowacamp/storage/global/error/ErrorCode.java
  src/main/java/com/woowacamp/storage/global/error/GlobalExceptionHandler.java
  src/main/resources/application.yml
Labels: ✅기능 개발

#26 [BE] 배포 스크립트 작성
  .github/workflows/deploy.yml
Labels: 🚀배포 작업

#27 [BE] 파일/폴더를 공유한다.
  src/main/java/com/woowacamp/storage/domain/file/controller/FileController.java
  src/main/java/com/woowacamp/storage/domain/file/controller/MultipartFileController.java
  src/main/java/com/woowacamp/storage/domain/file/dto/FileMoveDto.java
  src/main/java/com/woowacamp/storage/domain/file/dto/FormMetadataDto.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadata.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadataFactory.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileCustomRepository.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileCustomRepositoryImpl.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/file/service/FileService.java
  src/main/java/com/woowacamp/storage/domain/file/service/S3FileService.java
  src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/GetFolderContentsRequestParams.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/request/CreateFolderReqDto.java
  src/main/java/com/woowacamp/storage/domain/folder/dto/request/FolderMoveDto.java
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadata.java
  src/main/java/com/woowacamp/storage/domain/folder/entity/FolderMetadataFactory.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderCustomRepositoryImpl.java
  src/main/java/com/woowacamp/storage/domain/folder/repository/FolderMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
  src/main/java/com/woowacamp/storage/domain/shredlink/controller/SharedLinkController.java
  src/main/java/com/woowacamp/storage/domain/shredlink/dto/request/CancelSharedLinkRequestDto.java
  src/main/java/com/woowacamp/storage/domain/shredlink/dto/request/MakeSharedLinkRequestDto.java
  src/main/java/com/woowacamp/storage/domain/shredlink/entity/SharedLink.java
  src/main/java/com/woowacamp/storage/domain/shredlink/entity/SharedLinkFactory.java
  src/main/java/com/woowacamp/storage/domain/shredlink/repository/SharedLinkRepository.java
  src/main/java/com/woowacamp/storage/domain/shredlink/service/SharedLinkService.java
  src/main/java/com/woowacamp/storage/domain/user/service/UserService.java
  src/main/java/com/woowacamp/storage/global/annotation/CheckDto.java
  src/main/java/com/woowacamp/storage/global/annotation/CheckField.java
  src/main/java/com/woowacamp/storage/global/annotation/RequestType.java
  src/main/java/com/woowacamp/storage/global/aop/PermissionCheckAspect.java
  src/main/java/com/woowacamp/storage/global/aop/PermissionFieldsDto.java
  src/main/java/com/woowacamp/storage/global/aop/PermissionHandler.java
  src/main/java/com/woowacamp/storage/global/aop/type/FieldType.java
  src/main/java/com/woowacamp/storage/global/aop/type/FileType.java
  src/main/java/com/woowacamp/storage/global/constant/CommonConstant.java
  src/main/java/com/woowacamp/storage/global/constant/PermissionType.java
  src/main/java/com/woowacamp/storage/global/error/ErrorCode.java
  src/main/java/com/woowacamp/storage/global/util/UrlUtil.java
  src/test/java/com/woowacamp/storage/global/aop/PermissionHandlerTest.java
Labels: ✅기능 개발

#23 [BE] 썸네일을 추출한다.
  src/main/java/com/woowacamp/storage/domain/file/controller/MultipartFileController.java
  src/main/java/com/woowacamp/storage/domain/file/dto/FileMetadataDto.java
  src/main/java/com/woowacamp/storage/domain/file/dto/UploadContext.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadata.java
  src/main/java/com/woowacamp/storage/domain/file/entity/FileMetadataFactory.java
  src/main/java/com/woowacamp/storage/domain/file/repository/FileMetadataRepository.java
  src/main/java/com/woowacamp/storage/domain/file/service/FileService.java
  src/main/java/com/woowacamp/storage/domain/file/service/FileWriterThreadPool.java
  src/main/java/com/woowacamp/storage/domain/file/service/S3FileService.java
  src/main/java/com/woowacamp/storage/domain/file/service/ThumbnailWriterThreadPool.java
  src/main/java/com/woowacamp/storage/domain/folder/service/FolderService.java
  src/main/java/com/woowacamp/storage/global/constant/CommonConstant.java
  src/main/java/com/woowacamp/storage/global/scheduler/AbortedUploadDeleteScheduler.java
  src/main/java/com/woowacamp/storage/global/scheduler/FailFileDeleteScheduler.java
  src/main/java/com/woowacamp/storage/global/scheduler/OrphanFileDeleteScheduler.java
Labels: ✅기능 개발

#29 파일 삭제시 상위 폴더들의 사이즈 감소
  src/main/java/com/woowacamp/storage/domain/file/service/FileService.java
Labels: ✅기능 개발

#31 [BE] 사용되지 않는 기능 제거 및 권한 에러 수정
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/woowacamp/storage/domain/folder/controller/FolderController.java
  src/main/java/com/woowacamp/storage/global/aop/PermissionHandler.java
  src/main/java/com/woowacamp/storage/global/constant/CommonConstant.java
  src/main/resources/application.yml
Labels: 🐞버그 해결

#36 Hot fix
  .github/workflows/deploy.yml
  src/main/java/com/woowacamp/storage/domain/file/controller/MultipartFileController.java
  src/main/resources/application.yml
Labels: 🐞버그 해결, ✅기능 개발, 🚀배포 작업
